@startuml eco-backend

!theme plain
top to bottom direction
skinparam linetype ortho

class Comment {
   content: text
   createdAt: timestamp(3)
   updatedAt: timestamp(3)
   userId: text
   postId: text
   id: text
}
class Post {
   title: text
   content: text
   createdAt: timestamp(3)
   updatedAt: timestamp(3)
   userId: text
   id: text
}
class Reaction {
   createdAt: timestamp(3)
   updatedAt: timestamp(3)
   isLike: boolean
   userId: text
   postId: text
}
class User {
   email: text
   createdAt: timestamp(3)
   updatedAt: timestamp(3)
   id: text
}

Comment   -[#595959,plain]-^  Post     : "postId:id"
Comment   -[#595959,plain]-^  User     : "userId:id"
Post      -[#595959,plain]-^  User     : "userId:id"
Reaction  -[#595959,plain]-^  Post     : "postId:id"
Reaction  -[#595959,plain]-^  User     : "userId:id"
@enduml
