version: "3.9"

services:
  activity:
    container_name: activity
    platform: linux/amd64
    image: jdrouet/docker-activity:canary
    build: ./docker-activity
    command: file --format csv /data/output.csv
    volumes:
      # - /sys/class/powercap:/sys/class/powercap:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./result:/data
    depends_on:
      - postgres
      - mysql
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
